// 143/client/src/lib/BranchManager.svelte
<script>
  import { wsClient } from './websocket.js';

  export let showBranchesPanel = false;
  export let showCreateBranchModal = false;
  export let showMergeModal = false;
  export let showConflictModal = false;
  export let newBranchName = '';
  export let mergeSourceBranch = null;
  export let mergeTargetBranch = null;
  export let conflictResolutions = [];

  $: branches = $wsClient.branches || [];
  $: currentBranchId = $wsClient.branchId;
  $: merges = $wsClient.merges || [];
  $: currentMerge = $wsClient.currentMerge;
  $: mergeConflicts = $wsClient.mergeConflicts || [];

  function handleCreateBranch() {
    if (newBranchName.trim()) {
      wsClient.createBranch(newBranchName.trim());
      newBranchName = '';
      showCreateBranchModal = false;
    }
  }

  function handleSwitchBranch(branchId) {
    if (branchId !== currentBranchId) {
      wsClient.switchBranch(branchId);
    }
  }

  function handleDeleteBranch(branchId, e) {
    e.stopPropagation();
    if (confirm('Are you sure you want to delete this branch?')) {
      wsClient.deleteBranch(branchId);
    }
  }

  function handleMerge() {
    if (mergeSourceBranch && mergeTargetBranch && mergeSourceBranch !== mergeTargetBranch) {
      wsClient.mergeBranches(mergeSourceBranch, mergeTargetBranch);
      showMergeModal = false;
    }
  }

  function resolveConflict(conflict, action) {
    const existing = conflictResolutions.find(r => 
      (r.nodeId && (r.nodeId === conflict.nodeId || r.nodeId === conflict.sourceNodeId || r.nodeId === conflict.targetNodeId)) ||
      (r.connectionId && r.connectionId === conflict.connectionId)
    );

    if (existing) {
      existing.action = action;
    } else {
      const resolution = {
        action,
        nodeId: conflict.nodeId || conflict.sourceNodeId,
        connectionId: conflict.connectionId
      };
      conflictResolutions.push(resolution);
    }
  }

  function handleApplyMerge() {
    wsClient.resolveMerge(currentMerge.id, true, conflictResolutions);
    showConflictModal = false;
    conflictResolutions = [];
  }

  function handleAbortMerge() {
    wsClient.resolveMerge(currentMerge.id, false);
    showConflictModal = false;
    conflictResolutions = [];
  }

  function getConflictTypeLabel(type) {
    const labels = {
      'node_conflict': 'Node Property Conflict',
      'node_overlap': 'Node Position Conflict',
      'spatial_overlap': 'Spatial Overlap',
      'connection_conflict': 'Connection Conflict',
      'broken_connection': 'Broken Connection'
    };
    return labels[type] || type;
  }
</script>

{#if showBranchesPanel}
  <div class="branches-panel">
    <div class="panel-header">
      <h3>Branches</h3>
      <button class="btn-close" onclick={() => showBranchesPanel = false}>×</button>
    </div>

    <div class="panel-actions">
      <button class="btn btn-primary" onclick={() => showCreateBranchModal = true}>
        + New Branch
      </button>
      <button class="btn btn-secondary" onclick={() => showMergeModal = true}>
        Merge
      </button>
    </div>

    <div class="branches-list">
      {#each branches as branch}
        <div 
          class="branch-item {branch.id === currentBranchId ? 'current' : ''}"
          onclick={() => handleSwitchBranch(branch.id)}
        >
          <div class="branch-info">
            <span class="branch-name">{branch.name}</span>
            <span class="branch-version">v{branch.latest_version || 0}</span>
          </div>
          <div class="branch-actions">
            {#if branch.name !== 'main'}
              <button class="btn-icon" onclick={(e) => handleDeleteBranch(branch.id, e)} title="Delete">
                🗑️
              </button>
            {/if}
          </div>
        </div>
      {/each}
    </div>

    {#if merges.length > 0}
      <div class="merges-section">
        <h4>Merge History</h4>
        <div class="merges-list">
          {#each merges as merge}
            <div class="merge-item">
              <div class="merge-info">
                <span class="merge-branches">
                  {merge.source_branch_name} → {merge.target_branch_name}
                </span>
                <span class="merge-status status-{merge.status}">{merge.status}</span>
              </div>
              <div class="merge-date">
                {new Date(merge.created_at).toLocaleString()}
              </div>
            </div>
          {/each}
        </div>
      </div>
    {/if}
  </div>

  {#if showCreateBranchModal}
    <div class="modal-overlay" onclick={() => showCreateBranchModal = false}>
      <div class="modal" onclick={(e) => e.stopPropagation()}>
        <h2>Create Branch</h2>
        <div class="form-group">
          <label>Branch Name</label>
          <input 
            type="text" 
            bind:value={newBranchName} 
            placeholder="Enter branch name"
            on:keydown={(e) => e.key === 'Enter' && handleCreateBranch()}
          />
        </div>
        <div class="form-hint">
          Branch will be created from current branch ({branches.find(b => b.id === currentBranchId)?.name || 'main'})
        </div>
        <div class="modal-actions">
          <button class="btn btn-ghost" onclick={() => showCreateBranchModal = false}>
            Cancel
          </button>
          <button class="btn btn-primary" onclick={handleCreateBranch}>
            Create
          </button>
        </div>
      </div>
    </div>
  {/if}

  {#if showMergeModal}
    <div class="modal-overlay" onclick={() => showMergeModal = false}>
      <div class="modal" onclick={(e) => e.stopPropagation()}>
        <h2>Merge Branches</h2>
        <div class="form-group">
          <label>Source Branch</label>
          <select bind:value={mergeSourceBranch}>
            <option value={null}>Select source branch</option>
            {#each branches as branch}
              {#if branch.id !== mergeTargetBranch}
                <option value={branch.id}>{branch.name}</option>
              {/if}
            {/each}
          </select>
        </div>
        <div class="form-group">
          <label>Target Branch</label>
          <select bind:value={mergeTargetBranch}>
            <option value={null}>Select target branch</option>
            {#each branches as branch}
              {#if branch.id !== mergeSourceBranch}
                <option value={branch.id}>{branch.name}</option>
              {/if}
            {/each}
          </select>
        </div>
        <div class="modal-actions">
          <button class="btn btn-ghost" onclick={() => showMergeModal = false}>
            Cancel
          </button>
          <button class="btn btn-primary" onclick={handleMerge}>
            Merge
          </button>
        </div>
      </div>
    </div>
  {/if}
{/if}

{#if mergeConflicts.length > 0 && currentMerge}
  <div class="conflict-overlay">
    <div class="conflict-modal">
      <div class="conflict-header">
        <h2>Merge Conflicts Detected</h2>
        <p>{mergeConflicts.length} conflict(s) need to be resolved</p>
      </div>

      <div class="conflicts-list">
        {#each mergeConflicts as conflict}
          <div class="conflict-item">
            <div class="conflict-type">{getConflictTypeLabel(conflict.type)}</div>
            <div class="conflict-description">{conflict.description}</div>

            {#if conflict.type === 'node_conflict' || conflict.type === 'node_overlap'}
              <div class="conflict-compare">
                <div class="compare-side">
                  <h4>Source Branch</h4>
                  {#if conflict.source}
                    <p>Text: {conflict.source.text}</p>
                    <p>Color: {conflict.source.color}</p>
                    <p>Position: ({conflict.source.x}, {conflict.source.y})</p>
                  {/if}
                </div>
                <div class="compare-side">
                  <h4>Target Branch</h4>
                  {#if conflict.target}
                    <p>Text: {conflict.target.text}</p>
                    <p>Color: {conflict.target.color}</p>
                    <p>Position: ({conflict.target.x}, {conflict.target.y})</p>
                  {/if}
                </div>
              </div>
            {/if}

            {#if conflict.type === 'spatial_overlap'}
              <div class="conflict-compare">
                <div class="compare-side">
                  <h4>Node in Source</h4>
                  <p>Text: {conflict.sourceNode.text}</p>
                  <p>Position: ({conflict.sourceNode.x}, {conflict.sourceNode.y})</p>
                </div>
                <div class="compare-side">
                  <h4>Node in Target</h4>
                  <p>Text: {conflict.targetNode.text}</p>
                  <p>Position: ({conflict.targetNode.x}, {conflict.targetNode.y})</p>
                </div>
              </div>
            {/if}

            {#if conflict.type === 'broken_connection'}
              <div class="conflict-warning">
                ⚠️ Connection may break due to missing nodes
                {#if conflict.missingFrom}
                  <p>Missing source node: {conflict.connection.from}</p>
                {/if}
                {#if conflict.missingTo}
                  <p>Missing target node: {conflict.connection.to}</p>
                {/if}
              </div>
            {/if}

            <div class="conflict-resolutions">
              <button 
                class="btn btn-source"
                onclick={() => resolveConflict(conflict, 'keep_source')}
              >
                Keep Source
              </button>
              <button 
                class="btn btn-target"
                onclick={() => resolveConflict(conflict, 'keep_target')}
              >
                Keep Target
              </button>
              <button 
                class="btn btn-skip"
                onclick={() => resolveConflict(conflict, 'skip')}
              >
                Skip
              </button>
            </div>
          </div>
        {/each}
      </div>

      <div class="conflict-actions">
        <button class="btn btn-ghost" onclick={handleAbortMerge}>
          Abort Merge
        </button>
        <button class="btn btn-primary" onclick={handleApplyMerge}>
          Apply Merge
        </button>
      </div>
    </div>
  </div>
{/if}

<style>
  .branches-panel {
    position: fixed;
    right: 0;
    top: 60px;
    width: 320px;
    height: calc(100vh - 60px);
    background: var(--bg-primary);
    border-left: 1px solid var(--border);
    box-shadow: var(--shadow-lg);
    z-index: 100;
    display: flex;
    flex-direction: column;
  }

  .panel-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 16px;
    border-bottom: 1px solid var(--border);
  }

  .panel-header h3 {
    margin: 0;
    font-size: 16px;
  }

  .btn-close {
    background: none;
    border: none;
    font-size: 24px;
    cursor: pointer;
    color: var(--text-secondary);
  }

  .panel-actions {
    padding: 16px;
    display: flex;
    gap: 8px;
    border-bottom: 1px solid var(--border);
  }

  .btn {
    padding: 8px 16px;
    border-radius: 6px;
    font-size: 14px;
    font-weight: 500;
    cursor: pointer;
    transition: all 0.2s;
  }

  .btn-primary {
    background: var(--primary);
    color: white;
    border: none;
  }

  .btn-primary:hover {
    background: var(--primary-hover);
  }

  .btn-secondary {
    background: var(--bg-tertiary);
    color: var(--text-primary);
    border: none;
  }

  .btn-ghost {
    background: transparent;
    color: var(--text-secondary);
    border: none;
  }

  .btn-ghost:hover {
    background: var(--bg-tertiary);
  }

  .btn-icon {
    background: none;
    border: none;
    cursor: pointer;
    padding: 4px;
    font-size: 14px;
  }

  .branches-list {
    flex: 1;
    overflow-y: auto;
    padding: 8px;
  }

  .branch-item {
    padding: 12px;
    border-radius: 8px;
    cursor: pointer;
    display: flex;
    justify-content: space-between;
    align-items: center;
    transition: background 0.2s;
  }

  .branch-item:hover {
    background: var(--bg-secondary);
  }

  .branch-item.current {
    background: var(--primary);
    color: white;
  }

  .branch-info {
    display: flex;
    flex-direction: column;
  }

  .branch-name {
    font-weight: 500;
  }

  .branch-version {
    font-size: 12px;
    opacity: 0.7;
  }

  .branch-actions {
    display: flex;
    gap: 4px;
  }

  .merges-section {
    padding: 16px;
    border-top: 1px solid var(--border);
  }

  .merges-section h4 {
    margin: 0 0 12px 0;
    font-size: 14px;
    color: var(--text-secondary);
  }

  .merges-list {
    max-height: 200px;
    overflow-y: auto;
  }

  .merge-item {
    padding: 8px;
    border-radius: 6px;
    background: var(--bg-secondary);
    margin-bottom: 8px;
  }

  .merge-info {
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  .merge-branches {
    font-size: 12px;
    font-weight: 500;
  }

  .merge-status {
    font-size: 11px;
    padding: 2px 8px;
    border-radius: 10px;
    text-transform: uppercase;
  }

  .status-resolved {
    background: #10b981;
    color: white;
  }

  .status-pending {
    background: #fbbf24;
    color: #78350f;
  }

  .status-conflicted {
    background: #ef4444;
    color: white;
  }

  .merge-date {
    font-size: 11px;
    color: var(--text-secondary);
    margin-top: 4px;
  }

  .modal-overlay {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: rgba(0, 0, 0, 0.5);
    display: flex;
    justify-content: center;
    align-items: center;
    z-index: 200;
  }

  .modal {
    background: var(--bg-primary);
    border-radius: 12px;
    padding: 24px;
    min-width: 400px;
    max-width: 500px;
  }

  .modal h2 {
    margin: 0 0 20px 0;
  }

  .form-group {
    margin-bottom: 16px;
  }

  .form-group label {
    display: block;
    margin-bottom: 8px;
    font-size: 14px;
    font-weight: 500;
  }

  .form-group input,
  .form-group select {
    width: 100%;
    padding: 10px 12px;
    border: 1px solid var(--border);
    border-radius: 8px;
    font-size: 14px;
  }

  .form-hint {
    font-size: 12px;
    color: var(--text-secondary);
    margin-bottom: 16px;
  }

  .modal-actions {
    display: flex;
    justify-content: flex-end;
    gap: 12px;
  }

  .conflict-overlay {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: rgba(0, 0, 0, 0.7);
    display: flex;
    justify-content: center;
    align-items: center;
    z-index: 300;
  }

  .conflict-modal {
    background: var(--bg-primary);
    border-radius: 12px;
    padding: 24px;
    width: 800px;
    max-height: 80vh;
    display: flex;
    flex-direction: column;
  }

  .conflict-header {
    margin-bottom: 20px;
  }

  .conflict-header h2 {
    margin: 0 0 8px 0;
    color: #ef4444;
  }

  .conflicts-list {
    flex: 1;
    overflow-y: auto;
    padding: 0 8px;
  }

  .conflict-item {
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 16px;
    margin-bottom: 16px;
  }

  .conflict-type {
    font-weight: 600;
    color: var(--primary);
    margin-bottom: 8px;
  }

  .conflict-description {
    color: var(--text-secondary);
    margin-bottom: 12px;
  }

  .conflict-compare {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 16px;
    margin-bottom: 16px;
  }

  .compare-side {
    background: var(--bg-secondary);
    padding: 12px;
    border-radius: 8px;
  }

  .compare-side h4 {
    margin: 0 0 8px 0;
    font-size: 14px;
  }

  .compare-side p {
    margin: 4px 0;
    font-size: 13px;
  }

  .conflict-warning {
    background: #fef3c7;
    border: 1px solid #fbbf24;
    border-radius: 8px;
    padding: 12px;
    margin-bottom: 16px;
  }

  .conflict-resolutions {
    display: flex;
    gap: 8px;
  }

  .btn-source {
    background: #3b82f6;
    color: white;
    border: none;
  }

  .btn-target {
    background: #10b981;
    color: white;
    border: none;
  }

  .btn-skip {
    background: var(--bg-tertiary);
    color: var(--text-secondary);
    border: none;
  }

  .conflict-actions {
    display: flex;
    justify-content: flex-end;
    gap: 12px;
    padding-top: 16px;
    border-top: 1px solid var(--border);
  }
</style>

// 13/packages/client/src/components/BranchManager.vue
<template>
  <div class="branch-manager">
    <div class="branch-header">
      <h3>分支管理</h3>
      <button
        v-if="!showCreateForm"
        class="btn btn-primary btn-sm"
        @click="showCreateForm = true"
      >
        + 创建分支
      </button>
    </div>

    <div v-if="showCreateForm" class="create-form">
      <div class="form-group">
        <label>分支名称</label>
        <input
          v-model="newBranchName"
          type="text"
          placeholder="输入分支名称"
          maxlength="50"
        />
      </div>

      <div class="form-group">
        <label>从哪个分支创建</label>
        <select v-model="selectedParentBranchId">
          <option v-for="branch in branches" :key="branch.id" :value="branch.id">
            {{ branch.name }} (v{{ branch.currentVersion }})
          </option>
        </select>
      </div>

      <div class="form-group">
        <label>版本（可选，留空表示最新版本）</label>
        <input
          v-model.number="fromVersion"
          type="number"
          placeholder="输入版本号"
          min="0"
        />
      </div>

      <div class="form-group">
        <label>描述（可选）</label>
        <textarea
          v-model="newBranchDescription"
          placeholder="描述此分支的用途"
          rows="2"
        ></textarea>
      </div>

      <div class="form-actions">
        <button class="btn btn-secondary btn-sm" @click="cancelCreate">
          取消
        </button>
        <button
          class="btn btn-primary btn-sm"
          @click="createBranch"
          :disabled="!canCreateBranch || isCreating"
        >
          {{ isCreating ? '创建中...' : '创建' }}
        </button>
      </div>
    </div>

    <div class="branch-list">
      <div
        v-for="branch in branches"
        :key="branch.id"
        class="branch-item"
        :class="{
          'is-main': branch.isMain,
          'is-current': currentBranchId === branch.id,
        }"
      >
        <div class="branch-info">
          <div class="branch-name-row">
            <span class="branch-icon">
              {{ branch.isMain ? '🌿' : '🌱' }}
            </span>
            <span class="branch-name">{{ branch.name }}</span>
            <span v-if="branch.isMain" class="badge badge-main">main</span>
            <span v-if="currentBranchId === branch.id" class="badge badge-current">
              当前
            </span>
          </div>
          <div class="branch-meta">
            <span>版本: v{{ branch.currentVersion }}</span>
            <span>操作: {{ branch.operationCount }}</span>
            <span v-if="branch.parentBranchId">
              源自: {{ getParentBranchName(branch.parentBranchId) }}@v{{ branch.parentVersion }}
            </span>
          </div>
          <div v-if="branch.description" class="branch-desc">
            {{ branch.description }}
          </div>
        </div>

        <div class="branch-actions">
          <button
            v-if="currentBranchId !== branch.id"
            class="btn btn-secondary btn-sm"
            @click="switchToBranch(branch)"
          >
            切换
          </button>
          <button
            class="btn btn-info btn-sm"
            @click="showMergeDialog(branch)"
          >
            合并
          </button>
          <button
            v-if="!branch.isMain"
            class="btn btn-danger btn-sm"
            @click="confirmDeleteBranch(branch)"
          >
            删除
          </button>
        </div>
      </div>

      <div v-if="branches.length === 0" class="empty-state">
        暂无分支
      </div>
    </div>

    <div v-if="mergeDialogVisible" class="merge-dialog-overlay">
      <div class="merge-dialog">
        <h3>合并分支</h3>

        <div class="merge-content">
          <div class="form-group">
            <label>源分支（要合并的分支）</label>
            <div class="branch-preview">
              <strong>{{ sourceBranch?.name }}</strong>
              <span class="text-muted">v{{ sourceBranch?.currentVersion }}</span>
            </div>
          </div>

          <div class="form-group">
            <label>目标分支（合并到哪个分支）</label>
            <select v-model="mergeTargetBranchId">
              <option
                v-for="branch in mergeableBranches"
                :key="branch.id"
                :value="branch.id"
              >
                {{ branch.name }} (v{{ branch.currentVersion }})
              </option>
            </select>
          </div>

          <div class="form-group">
            <label>合并策略</label>
            <select v-model="mergeStrategy">
              <option value="auto">自动（推荐）</option>
              <option value="ours">优先使用目标分支</option>
              <option value="theirs">优先使用源分支</option>
            </select>
          </div>

          <div v-if="mergePreview" class="merge-preview-box">
            <h4>合并预览</h4>
            <div v-if="mergePreview.hasConflicts">
              <div class="conflict-warning">
                ⚠️ 检测到 {{ mergePreview.conflictCount }} 个冲突
              </div>
              <div class="conflict-list">
                <div
                  v-for="(conflict, index) in mergePreview.sampleConflicts"
                  :key="index"
                  class="conflict-item"
                >
                  <span class="conflict-type">{{ conflict.type === 'node' ? '节点' : '边' }}</span>
                  <span class="conflict-target">{{ conflict.targetId }}</span>
                  <span v-if="conflict.autoResolved" class="badge badge-auto">自动解决</span>
                </div>
              </div>
            </div>
            <div v-else class="no-conflicts">
              ✅ 无冲突，预计应用 {{ mergePreview.estimatedNewOperations }} 个操作
            </div>
          </div>
        </div>

        <div class="merge-actions">
          <button class="btn btn-secondary" @click="closeMergeDialog">
            取消
          </button>
          <button
            class="btn btn-primary"
            @click="executeMerge"
            :disabled="!canMerge || isMerging"
          >
            {{ isMerging ? '合并中...' : '合并' }}
          </button>
        </div>
      </div>
    </div>

    <div v-if="deleteDialogVisible" class="delete-dialog-overlay">
      <div class="delete-dialog">
        <h3>确认删除分支</h3>
        <p>
          确定要删除分支 <strong>"{{ branchToDelete?.name }}"</strong> 吗？
          此操作无法撤销。
        </p>
        <div class="delete-actions">
          <button class="btn btn-secondary" @click="cancelDelete">
            取消
          </button>
          <button
            class="btn btn-danger"
            @click="deleteBranch"
            :disabled="isDeleting"
          >
            {{ isDeleting ? '删除中...' : '确认删除' }}
          </button>
        </div>
      </div>
    </div>

    <div v-if="error" class="error-message">
      {{ error }}
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue';
import { apiService } from '../services/api';
import type { Branch, MergeResult } from '@collaborative-graph/shared';

const props = defineProps<{
  graphId: string;
  currentBranchId: string | null;
}>();

const emit = defineEmits<{
  (e: 'switch', branch: Branch): void;
  (e: 'merged', result: MergeResult): void;
  (e: 'error', message: string): void;
}>();

const branches = ref<Branch[]>([]);
const loading = ref(false);
const error = ref<string | null>(null);

const showCreateForm = ref(false);
const newBranchName = ref('');
const newBranchDescription = ref('');
const selectedParentBranchId = ref<string | null>(null);
const fromVersion = ref<number | null>(null);
const isCreating = ref(false);

const mergeDialogVisible = ref(false);
const sourceBranch = ref<Branch | null>(null);
const mergeTargetBranchId = ref<string | null>(null);
const mergeStrategy = ref<'ours' | 'theirs' | 'auto'>('auto');
const mergePreview = ref<{
  hasConflicts: boolean;
  conflictCount: number;
  sampleConflicts: Array<{
    type: 'node' | 'edge';
    targetId: string;
    autoResolved: boolean;
  }>;
  estimatedNewOperations: number;
} | null>(null);
const isMerging = ref(false);

const deleteDialogVisible = ref(false);
const branchToDelete = ref<Branch | null>(null);
const isDeleting = ref(false);

const canCreateBranch = computed(() => {
  return newBranchName.value.trim().length > 0 && !isCreating.value;
});

const mergeableBranches = computed(() => {
  if (!sourceBranch.value) return [];
  return branches.value.filter(
    (b) => b.id !== sourceBranch.value!.id && !b.isMain,
  );
});

const canMerge = computed(() => {
  return (
    sourceBranch.value &&
    mergeTargetBranchId.value &&
    mergeTargetBranchId.value !== sourceBranch.value.id &&
    !isMerging.value
  );
});

async function loadBranches() {
  loading.value = true;
  error.value = null;

  try {
    branches.value = await apiService.listBranches(props.graphId);

    if (branches.value.length > 0) {
      const mainBranch = branches.value.find((b) => b.isMain);
      if (mainBranch && !selectedParentBranchId.value) {
        selectedParentBranchId.value = mainBranch.id;
      }
    }
  } catch (err) {
    error.value = err instanceof Error ? err.message : '加载分支失败';
    emit('error', error.value);
  } finally {
    loading.value = false;
  }
}

function getParentBranchName(parentId: string): string {
  const parent = branches.value.find((b) => b.id === parentId);
  return parent?.name || '未知分支';
}

function cancelCreate() {
  showCreateForm.value = false;
  newBranchName.value = '';
  newBranchDescription.value = '';
  fromVersion.value = null;
}

async function createBranch() {
  if (!canCreateBranch.value) return;

  isCreating.value = true;
  error.value = null;

  try {
    await apiService.createBranch(props.graphId, {
      name: newBranchName.value.trim(),
      userId: 'user',
      fromBranchId: selectedParentBranchId.value || undefined,
      fromVersion: fromVersion.value || undefined,
      description: newBranchDescription.value || undefined,
    });

    cancelCreate();
    await loadBranches();
  } catch (err) {
    error.value = err instanceof Error ? err.message : '创建分支失败';
  } finally {
    isCreating.value = false;
  }
}

function switchToBranch(branch: Branch) {
  emit('switch', branch);
}

function showMergeDialog(branch: Branch) {
  sourceBranch.value = branch;
  mergeTargetBranchId.value = props.currentBranchId;
  mergeDialogVisible.value = true;
  mergePreview.value = null;

  if (mergeTargetBranchId.value) {
    loadMergePreview();
  }
}

watch(mergeTargetBranchId, () => {
  if (mergeTargetBranchId.value && sourceBranch.value) {
    loadMergePreview();
  }
});

async function loadMergePreview() {
  if (!sourceBranch.value || !mergeTargetBranchId.value) return;

  try {
    mergePreview.value = await apiService.previewMerge(
      props.graphId,
      sourceBranch.value.id,
      mergeTargetBranchId.value,
    );
  } catch (err) {
    console.error('Failed to load merge preview:', err);
  }
}

function closeMergeDialog() {
  mergeDialogVisible.value = false;
  sourceBranch.value = null;
  mergeTargetBranchId.value = null;
  mergePreview.value = null;
}

async function executeMerge() {
  if (!canMerge.value || !sourceBranch.value) return;

  isMerging.value = true;
  error.value = null;

  try {
    const result = await apiService.mergeBranches(props.graphId, {
      sourceBranchId: sourceBranch.value.id,
      targetBranchId: mergeTargetBranchId.value!,
      userId: 'user',
      strategy: mergeStrategy.value,
    });

    emit('merged', result);
    closeMergeDialog();
    await loadBranches();
  } catch (err) {
    error.value = err instanceof Error ? err.message : '合并失败';
  } finally {
    isMerging.value = false;
  }
}

function confirmDeleteBranch(branch: Branch) {
  branchToDelete.value = branch;
  deleteDialogVisible.value = true;
}

function cancelDelete() {
  deleteDialogVisible.value = false;
  branchToDelete.value = null;
}

async function deleteBranch() {
  if (!branchToDelete.value) return;

  isDeleting.value = true;
  error.value = null;

  try {
    await apiService.deleteBranch(
      props.graphId,
      branchToDelete.value.id,
      'user',
    );
    cancelDelete();
    await loadBranches();
  } catch (err) {
    error.value = err instanceof Error ? err.message : '删除分支失败';
  } finally {
    isDeleting.value = false;
  }
}

onMounted(() => {
  loadBranches();
});

watch(
  () => props.graphId,
  () => {
    loadBranches();
  },
);
</script>

<style scoped>
.branch-manager {
  background: var(--bg-secondary, #1e1e1e);
  border-radius: 8px;
  padding: 16px;
  color: var(--text-primary, #e0e0e0);
}

.branch-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 16px;
}

.branch-header h3 {
  margin: 0;
  font-size: 16px;
  font-weight: 600;
}

.create-form {
  background: var(--bg-tertiary, #252525);
  padding: 16px;
  border-radius: 8px;
  margin-bottom: 16px;
}

.form-group {
  margin-bottom: 12px;
}

.form-group label {
  display: block;
  margin-bottom: 4px;
  font-size: 12px;
  color: var(--text-secondary, #9ca3af);
}

.form-group input,
.form-group select,
.form-group textarea {
  width: 100%;
  padding: 8px 12px;
  background: var(--bg-primary, #1a1a1a);
  border: 1px solid var(--border-color, #374151);
  border-radius: 6px;
  color: var(--text-primary, #e0e0e0);
  font-size: 14px;
}

.form-group input:focus,
.form-group select:focus,
.form-group textarea:focus {
  outline: none;
  border-color: var(--accent-color, #3b82f6);
}

.form-actions {
  display: flex;
  gap: 8px;
  justify-content: flex-end;
  margin-top: 16px;
}

.branch-list {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.branch-item {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  padding: 12px;
  background: var(--bg-tertiary, #252525);
  border-radius: 8px;
  border: 1px solid transparent;
  transition: border-color 0.2s;
}

.branch-item:hover {
  border-color: var(--border-color, #374151);
}

.branch-item.is-current {
  border-color: var(--accent-color, #3b82f6);
}

.branch-item.is-main {
  background: var(--bg-accent, #1f2937);
}

.branch-name-row {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 4px;
}

.branch-icon {
  font-size: 18px;
}

.branch-name {
  font-weight: 600;
  font-size: 14px;
}

.branch-meta {
  display: flex;
  gap: 16px;
  font-size: 12px;
  color: var(--text-secondary, #9ca3af);
  margin-bottom: 4px;
}

.branch-desc {
  font-size: 12px;
  color: var(--text-tertiary, #6b7280);
  font-style: italic;
}

.branch-actions {
  display: flex;
  gap: 8px;
}

.badge {
  padding: 2px 8px;
  border-radius: 4px;
  font-size: 11px;
  font-weight: 500;
}

.badge-main {
  background: var(--accent-color, #3b82f6);
  color: white;
}

.badge-current {
  background: var(--success-color, #10b981);
  color: white;
}

.badge-auto {
  background: var(--warning-color, #f59e0b);
  color: white;
}

.btn {
  padding: 6px 12px;
  border-radius: 6px;
  font-size: 13px;
  font-weight: 500;
  cursor: pointer;
  border: none;
  transition: all 0.2s;
}

.btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.btn-primary {
  background: var(--accent-color, #3b82f6);
  color: white;
}

.btn-primary:hover:not(:disabled) {
  background: var(--accent-hover, #2563eb);
}

.btn-secondary {
  background: var(--bg-tertiary, #374151);
  color: var(--text-primary, #e0e0e0);
}

.btn-secondary:hover:not(:disabled) {
  background: var(--bg-hover, #4b5563);
}

.btn-info {
  background: var(--info-color, #06b6d4);
  color: white;
}

.btn-info:hover:not(:disabled) {
  background: var(--info-hover, #0891b2);
}

.btn-danger {
  background: var(--danger-color, #ef4444);
  color: white;
}

.btn-danger:hover:not(:disabled) {
  background: var(--danger-hover, #dc2626);
}

.btn-sm {
  padding: 4px 10px;
  font-size: 12px;
}

.merge-dialog-overlay,
.delete-dialog-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.7);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;
}

.merge-dialog,
.delete-dialog {
  background: var(--bg-secondary, #1e1e1e);
  border-radius: 12px;
  padding: 24px;
  max-width: 500px;
  width: 90%;
  max-height: 80vh;
  overflow-y: auto;
}

.merge-dialog h3,
.delete-dialog h3 {
  margin: 0 0 20px 0;
  font-size: 18px;
}

.branch-preview {
  padding: 10px 12px;
  background: var(--bg-tertiary, #252525);
  border-radius: 6px;
  font-size: 14px;
}

.text-muted {
  color: var(--text-secondary, #9ca3af);
  margin-left: 8px;
}

.merge-preview-box {
  margin-top: 16px;
  padding: 12px;
  background: var(--bg-tertiary, #252525);
  border-radius: 8px;
}

.merge-preview-box h4 {
  margin: 0 0 12px 0;
  font-size: 14px;
  font-weight: 600;
}

.conflict-warning {
  color: var(--warning-color, #f59e0b);
  font-weight: 500;
  margin-bottom: 8px;
}

.no-conflicts {
  color: var(--success-color, #10b981);
  font-weight: 500;
}

.conflict-list {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.conflict-item {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 6px 10px;
  background: var(--bg-primary, #1a1a1a);
  border-radius: 4px;
  font-size: 13px;
}

.conflict-type {
  padding: 2px 8px;
  background: var(--danger-color, #ef4444);
  border-radius: 4px;
  font-size: 11px;
  color: white;
}

.conflict-target {
  font-family: monospace;
}

.merge-actions,
.delete-actions {
  display: flex;
  gap: 12px;
  justify-content: flex-end;
  margin-top: 24px;
}

.error-message {
  margin-top: 12px;
  padding: 10px;
  background: var(--danger-bg, #450a0a);
  color: var(--danger-color, #f87171);
  border-radius: 6px;
  font-size: 13px;
}

.empty-state {
  text-align: center;
  padding: 32px;
  color: var(--text-secondary, #9ca3af);
}
</style>
